import Image from "next/image";

interface Props {
  src: string;
  alt: string;
  width: number;
  height: number;
  caption?: string;
}

/**
 * Original data diagrams (public/diagrams/*, generated by
 * scripts/generate-diagrams.mjs from the same published pricing cited on
 * each page). SVGs skip the image optimizer via `unoptimized`.
 */
export default function DiagramFigure({ src, alt, width, height, caption }: Props) {
  return (
    <figure className="mb-8">
      <Image
        src={src}
        alt={alt}
        width={width}
        height={height}
        unoptimized
        loading="lazy"
        className="w-full h-auto rounded-xl border border-gray-200 bg-white"
      />
      {caption && (
        <figcaption className="text-xs text-gray-500 mt-2">{caption}</figcaption>
      )}
    </figure>
  );
}
